### ISSUE TITLE
Hide discount for payment method when there isn't one (instead of showing 0)

### ISSUE THREAD

**Issue by nattywebdev** [backdrop-contrib/uc_pma#3]
When there is no fee or discount for a particular payment method, could the line be hidden from the display on the Checkout page? Even if via css with a class applied to the row? Clearly this is an enhancement!

Zero discount shown when there is no discount/fee:
![image](https://github.com/backdrop-contrib/uc_pma/assets/54537636/fafb1a56-792e-462a-ba38-18b41962d3c7)

Correctly shown when there is a (non-zero) discount:
![image](https://github.com/backdrop-contrib/uc_pma/assets/54537636/defba390-bc02-4548-818a-2c7b65736877)

**Comment by bugfolder** [comment]
PR implementing this behavior is merged into HEAD.

**Comment by nattywebdev** [comment]
Wonderful. Thank you!
